POST http://localhost:3002/api/user/register HTTP/1.1
Content-Type: application/json

{
    "username": "lhnam1202",
    "password": "123123",
    "passwordConfirmation": "123123",
    "name": "hoang nam",
    "phone":"0123123123",
    "dob": "2000-04-23",
    "email": "lamtvu2@gmail.com"
}

###
POST http://localhost:3002/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "lhnam1201",
    "password": "123123"
}


###
GET http://localhost:3002/api/user/get-detail  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQ4NzY5NGM4Y2VlZjYxOThlNWFiMDYiLCJpYXQiOjE2MzIxNDMzMjksImV4cCI6MTYzMjIyOTcyOX0.4reC_Sie5VPL6_8KxPYtZpTLsdmvBLGiJNK3s6Rx8MY